In [ ]:
import numpy

In [ ]:
numpy.array

In [ ]:
import numpy

In [ ]:
a=numpy.array([1,2,3])
print(a)

In [ ]:
import numpy as ra

In [ ]:
a=ra.array([1,2,2.2,3])
print(a)

In [ ]:
import numpy as ra
b=ra.array([[1,2],[3,4],[4,5]])
print(b)

In [ ]:
import numpy as np
a=np.array([[1,2],[2,3],[4,5]],ndmin=2)
print(a)

In [ ]:
help(numpy)

In [ ]:
help(dir(numpy))

In [ ]:
print(dir(numpy))

In [ ]:
import numpy as np
a=np.array([1,2,3],dtype=complex)
print(a)

In [ ]:
dt=np.dtype('i4')
print(dt)

In [ ]:
import numpy as kk
df=kk.dtype(np.int32)
print(df)

In [ ]:
import numpy as np
student=np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')])
print(student)

In [ ]:
import numpy as kk
f=kk.array([[1,2,3],[1,2,3]])
print(f)

In [ ]:
a=kk.arange(10)
b=kk.arange(20)
print(a)
print(b)



In [ ]:
a=kk.arange(15).reshape(5,3)

In [ ]:
a

In [ ]:
print(a.ndim)
print(a.dtype)
print(a.size)

In [ ]:
help(a)

In [ ]:
b=kk.array([1.1,2.2,3.3])
b
print(b.ndim)
print(b.dtype)

In [ ]:
d=kk.eye(10)
d

In [ ]:
a=kk.linspace(1,20)
a

In [ ]:
a=kk.linspace(1,20,3)

In [ ]:
a

In [ ]:
b=kk.logspace(1,20,3)

In [ ]:
b

In [ ]:
q=kk.fromfunction(lambda i,j:i==j,(4,4))

In [ ]:
q

In [ ]:
a = kk.arange(15).reshape(3,5)
print(a)

In [ ]:
a*2


In [ ]:
a + a

In [ ]:
a*a

In [ ]:
b = a.transpose()
b

In [ ]:
a @ b


In [ ]:
print(a)
a.sum(axis=0)

In [ ]:
a

In [ ]:
a.sum()

In [ ]:
print(a.max())

In [ ]:
print(a.mid())

In [ ]:
print(a.min())

In [ ]:
b = a*kk.pi/10
print(b)

In [ ]:
c = kk.cos(b)
print(c)

In [ ]:
d = b + c 
d

In [ ]:
a = kk.arange(9)
a

In [ ]:
print(a[3])
print(a[2:3])

In [ ]:
a[:]

In [ ]:
a = kk.arange(15).reshape(3,5)
a

In [ ]:
a[1,3]

In [ ]:
a[0:2,0:]

In [ ]:
a[:,2]

In [ ]:
a = a.flatten()
print(a)

In [ ]:
a=a.flat()
print(a)

In [ ]:
a = kk.arange(10)
print(a)


In [ ]:
b=a
b is a

In [ ]:
b.shape = (2, 5)
print(b)
a.shape

In [ ]:
a = kk.arange(12).reshape(3,4)
a

In [ ]:

a[a>3]=0
a

In [ ]:
a[a==0]=-2

In [ ]:
a

In [ ]:
a==-2

In [13]:
import numpy as lk
M=32
N=64
xmin=ymin=0.0
xmax=ymax=1.0
x=lk.linspace(xmin,xmax,M,endpoint=False)
y=lk.linspace(ymin,ymax,N,endpoint=False)
print(x.shape)
print(y.shape)
print(x)
print(y)

(32,)
(64,)
[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 0.59375  0.609375
 0.625    0.640625 0.65625  0.671875 0.6875   0.703125 0.71875  0.734375
 0.75     0.765625 0.78125  0.796875 0.8125   0.828125 0.84375  0.859375
 0.875    0.890625 0.90625  0.921875 0.9375   0.953125 0.96875  0.984375]


In [12]:
M = 32
N = 64
xmin = ymin = 0.0
xmax = ymax = 1.0

x = lk.linspace(xmin, xmax, M, endpoint=False)
y = lk.linspace(ymin, ymax, N, endpoint=False)

print(x.shape)
print(y.shape)
print(y)
x

(32,)
(64,)
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 0.59375  0.609375
 0.625    0.640625 0.65625  0.671875 0.6875   0.703125 0.71875  0.734375
 0.75     0.765625 0.78125  0.796875 0.8125   0.828125 0.84375  0.859375
 0.875    0.890625 0.90625  0.921875 0.9375   0.953125 0.96875  0.984375]


array([0.     , 0.03125, 0.0625 , 0.09375, 0.125  , 0.15625, 0.1875 ,
       0.21875, 0.25   , 0.28125, 0.3125 , 0.34375, 0.375  , 0.40625,
       0.4375 , 0.46875, 0.5    , 0.53125, 0.5625 , 0.59375, 0.625  ,
       0.65625, 0.6875 , 0.71875, 0.75   , 0.78125, 0.8125 , 0.84375,
       0.875  , 0.90625, 0.9375 , 0.96875])

In [14]:
import time

In [15]:
help(time)

Help on built-in module time:

NAME
    time - This module provides various functions to manipulate time values.

DESCRIPTION
    There are two standard representations of time.  One is the number
    of seconds since the Epoch, in UTC (a.k.a. GMT).  It may be an integer
    or a floating point number (to represent fractions of seconds).
    The Epoch is system-defined; on Unix, it is generally January 1st, 1970.
    The actual value can be retrieved by calling gmtime(0).
    
    The other representation is a tuple of 9 integers giving local time.
    The tuple items are:
      year (including century, e.g. 1998)
      month (1-12)
      day (1-31)
      hours (0-23)
      minutes (0-59)
      seconds (0-59)
      weekday (0-6, Monday is 0)
      Julian day (day in the year, 1-366)
      DST (Daylight Savings Time) flag (-1, 0 or 1)
    If the DST flag is 0, the time is given in the regular time zone;
    if it is 1, the time is given in the DST time zone;
    if it is -1, mktime() sh

In [27]:
import time
t0=time.time()
g=lk.zeros((M,N))
print(g)
for i in range(M):
    for j in range(N):
        g[i,j]=lk.sin(2.0*lk.pi*x[i]*y[j])
t1=time.time()
print('time elasped:{}s'.format(t1-t0))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
time elasped:0.007997274398803711s


In [23]:
x2d, y2d = lk.meshgrid(x, y, indexing="ij")

print(x2d[:,0])
print(x2d[0,:])

print(y2d[:,0])
print(y2d[0,:])

[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 0.59375  0.609375
 0.625    0.640625 0.65625  0.671875 0.6875   0.703125 0.71875  0.734375
 0.75     

In [26]:
t0 = time.time()
g2 = lk.sin(2.0*lk.pi*x2d*y2d)
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.0 s


In [28]:
a=lk.array([1,2,3,4])
b=lk.array([4,5,6])
lk.concatenate([b,a])

array([4, 5, 6, 1, 2, 3, 4])

In [32]:
grid=lk.arange(40).reshape((5,8))
grid

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [35]:
left, right = lk.hsplit(grid, [4])
print(left)
print(right)

[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]
 [24 25 26 27]
 [32 33 34 35]]
[[ 4  5  6  7]
 [12 13 14 15]
 [20 21 22 23]
 [28 29 30 31]
 [36 37 38 39]]


In [38]:
x = lk.arange(1, 9)
print(x)
lk.add.reduce(x)

[1 2 3 4 5 6 7 8]


36

In [39]:
lk.multiply.reduce(x)

40320

In [40]:
lk.multiply.accumulate(x)

array([    1,     2,     6,    24,   120,   720,  5040, 40320],
      dtype=int32)